/// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSw3Change();
void onSw0Change();
void onSw1Change();
void onSw2Change();

float humid;
float input_2;
float light;
float soil_ec;
float soil_mois;
float soil_nitro;
float soil_ph;
float soil_phos;
float soil_potas;
float soil_temp;
float soil_tds;
float soil_salin;

float temp;
int dataOut1;
bool input_0;
bool input_1;
bool input_3;
bool relay_0;
bool relay_1;
bool relay_2;
bool relay_3;
bool sw_0;
bool sw_1;
bool sw_2;
bool sw_3;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humid, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(input_2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(light, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soil_ec, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soil_mois, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soil_nitro, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soil_ph, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soil_phos, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soil_salin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soil_tds, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soil_potas, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soil_temp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sw_3, READWRITE, ON_CHANGE, onSw3Change);
  ArduinoCloud.addProperty(temp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(dataOut1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(input_0, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(input_1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(input_3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(relay_0, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(relay_1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(relay_2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(relay_3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sw_0, READWRITE, ON_CHANGE, onSw0Change);
  ArduinoCloud.addProperty(sw_1, READWRITE, ON_CHANGE, onSw1Change);
  ArduinoCloud.addProperty(sw_2, READWRITE, ON_CHANGE, onSw2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
